name: GitHub Actions CI

on:
  push:
    branches: [ main ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ docs/** ]

jobs:
    test-local:
      name: +test-local
      runs-on: ubuntu-latest
      env:
        FORCE_COLOR: 1
        EARTHLY_CONVERSION_PARALLELISM: "5"
        EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
        EARTHLY_INSTALL_ID: "earthly-githubactions"
      steps:
        - uses: actions/checkout@v2
        - name: Download released earthly
          run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
        - name: Build latest earthly using released earthly
          run: earthly --use-inline-cache +for-linux
        - name: Execute test-local
          run: "./build/linux/amd64/earthly --use-inline-cache --save-inline-cache --no-output ./examples/tests/local+test-local"
        - name: Check previous run without the --push flag correctly prevented the file from being touched
          run: "! ls /tmp/earthly-test-local"
        - name: Execute test-local --push
          run: "./build/linux/amd64/earthly --use-inline-cache --save-inline-cache --no-output --push ./examples/tests/local+test-local"
        - name: Check --push cmd was run (and touched this file on the local disk)
          run: "ls /tmp/earthly-test-local"
        - name: Run general local tests (TODO this is re-testing the +test-local target)
          run: "./build/linux/amd64/earthly --use-inline-cache --save-inline-cache --no-output ./examples/tests/local+all"
        - name: Buildkit logs (runs on failure)
          run: docker logs earthly-buildkitd; cd /tmp/ac0887d7-fda7-4a1b-9873-054488c7e44d/; ls -la; for x in *; do echo "--- $x ---"; cat $x; done
          if: ${{ failure() || !failure() }}
